#!/usr/bin/python3
"""This module defines the main function."""
from api.v1.auth.auth import Auth

a = Auth()
print(Auth())
print(a.require_auth("/a", ["/api/v1/status/"]))
print(a.authorization_header())
print(a.current_user())